name: Deploy

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: TODO
        run: exit 0

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node Setup
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
      - name: Heroku Setup
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
          heroku git:remote --app $HEROKU_APP_NAME
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      - name: Build
        run: |
          yarn
          yarn build
      - name: Deploy
        run: |
          echo './node_modules' > .gitignore
          git add build
          git commit -m 'Commit build folder'
          git subtree push --prefix build heroku main
