name: Deploy

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '*.md'

jobs:
  static_code_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node Setup
        uses: actions/setup-node@v2
        with:
          node-version: 15
          registry-url: https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - name: Validate
        run: |
          yarn
          yarn validate

  deploy_to_staging_environment:
    needs: static_code_analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Heroku Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_STAGING_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          healthcheck: 'https://exfix-server-staging.herokuapp.com/api/ping'
          checkstring: 'pong'
        env:
          HD_HUSKY: 0 # Skip husky pre-push

  end_to_end_tests:
    needs: deploy_to_staging_environment
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder (TODO)
        run: exit 0

  promote_to_production:
    needs: end_to_end_tests
    runs-on: ubuntu-latest
    steps:
      - name: Heroku Setup
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
          heroku pipelines:promote -a $HEROKU_APP_NAME
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_STAGING_APP_NAME }}
